<?xml version="1.0"?>
<ecampaign>
	<code>CODE_RETOUR</code>
	<message>MESSAGE_RETOUR</message>
	<hlr>
		<number></number>
		<status_code></status_code>
		<status_msg></status_msg>
		<error_code></error_code>
		<error_permanent></error_permanent>
		<error_msg></error_msg>
		<imsi></imsi>
		<net_mcc></net_mcc>
		<net_mnc></net_mnc>
		<ported></ported>
		<net_orig></net_orig>
		<net_orig_prefix></net_orig_prefix>
		<net_orig_country></net_orig_country>
		<net_port></net_port>
		<net_port_prefix></net_port_prefix>
		<net_port_country></net_port_country>
	</hlr>
</ecampaign>